/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lbms;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
/**
 *
 * @author 91738
 */
public class custreg extends javax.swing.JFrame {
    Connection con = null;
    PreparedStatement pst = null;
    
    /**
     * Creates new form custreg
     */
    public custreg() {
        this.con = null;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        First_Name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        customer_Email_ID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        customer_Contact = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Gender = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        DOB = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        Age = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        customer_City = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        customer_State = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        register = new javax.swing.JLabel();
        Last_Name = new javax.swing.JTextField();
        customer_Address = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        customer_Pincode = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        customer_District = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        confpass = new javax.swing.JPasswordField();
        customer_password = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        ckpass = new javax.swing.JCheckBox();
        rSFotoCircle1 = new rojerusan.RSFotoCircle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1366, 768));

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 768));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRATION FORM");

        jPanel4.setPreferredSize(new java.awt.Dimension(746, 600));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("FIRST NAME: ");

        First_Name.setPreferredSize(new java.awt.Dimension(175, 35));
        First_Name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                First_NameFocusGained(evt);
            }
        });
        First_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                First_NameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("EMAIL ID:");

        customer_Email_ID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                customer_Email_IDFocusGained(evt);
            }
        });
        customer_Email_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_Email_IDActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("CONTACT NO.:");

        customer_Contact.setMinimumSize(new java.awt.Dimension(190, 35));
        customer_Contact.setPreferredSize(new java.awt.Dimension(190, 35));
        customer_Contact.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                customer_ContactFocusGained(evt);
            }
        });
        customer_Contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_ContactActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("LAST NAME:");

        Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "M", "F", "O" }));
        Gender.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Gender.setPreferredSize(new java.awt.Dimension(190, 35));
        Gender.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                GenderFocusGained(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("DATE OF BIRTH:");

        DOB.setText("DD/MM/YYYY");
        DOB.setPreferredSize(new java.awt.Dimension(190, 35));
        DOB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DOBFocusGained(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("DISTRICT:");

        Age.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AgeFocusGained(evt);
            }
        });
        Age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("ADDRESS:");

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("CITY:");

        customer_City.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                customer_CityFocusGained(evt);
            }
        });
        customer_City.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_CityActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("PINCODE:");

        customer_State.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                customer_StateFocusGained(evt);
            }
        });
        customer_State.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_StateActionPerformed(evt);
            }
        });

        jCheckBox1.setText("THE ABOVE INFORMATION ENTERED IS CORRECT.");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        register.setBackground(new java.awt.Color(0, 0, 102));
        register.setFont(new java.awt.Font("Arial Black", 1, 22)); // NOI18N
        register.setForeground(new java.awt.Color(255, 255, 255));
        register.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        register.setText("REGISTER");
        register.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        register.setOpaque(true);
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerMouseClicked(evt);
            }
        });

        Last_Name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Last_NameFocusGained(evt);
            }
        });
        Last_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Last_NameActionPerformed(evt);
            }
        });

        customer_Address.setPreferredSize(new java.awt.Dimension(556, 35));
        customer_Address.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                customer_AddressFocusGained(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("AGE:");

        customer_Pincode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                customer_PincodeFocusGained(evt);
            }
        });
        customer_Pincode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_PincodeActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("STATE:");

        customer_District.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                customer_DistrictFocusGained(evt);
            }
        });
        customer_District.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_DistrictActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("PASSWORD:");

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("CONF. PSWD:");

        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("GENDER:");

        confpass.setText("jPasswordField1");
        confpass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                confpassFocusGained(evt);
            }
        });

        customer_password.setText("jPasswordField2");
        customer_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                customer_passwordFocusGained(evt);
            }
        });
        customer_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_passwordActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("NOTE: PASSWORD SHOULD CONTAIN MINIMUM 8 AND MAXIMUM 20  CHARACTERS WITH 1 UPPER CASE, 1 SPECIAL CHARACTER");
        jLabel3.setMaximumSize(new java.awt.Dimension(693, 14));
        jLabel3.setMinimumSize(new java.awt.Dimension(693, 14));
        jLabel3.setPreferredSize(new java.awt.Dimension(693, 14));

        ckpass.setText("Show Password");
        ckpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ckpassMouseClicked(evt);
            }
        });
        ckpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckpassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(First_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Last_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(customer_Email_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel16))
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(DOB, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(customer_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(44, 44, 44)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(customer_Address, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(customer_City, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                                .addComponent(customer_State, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                                .addComponent(customer_password)
                                                .addComponent(ckpass, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addGap(47, 47, 47)
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel9)
                                                .addComponent(jLabel17))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(customer_District, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                                .addComponent(customer_Pincode, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                                .addComponent(confpass))))))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jCheckBox1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(First_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Last_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customer_Email_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customer_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DOB, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customer_Address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customer_City, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customer_District, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(customer_Pincode, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(customer_State, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)))
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(confpass, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customer_password, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ckpass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(register)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176)
                .addComponent(rSFotoCircle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(260, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(rSFotoCircle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void First_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_First_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_First_NameActionPerformed

    private void customer_Email_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_Email_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customer_Email_IDActionPerformed

    private void customer_ContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_ContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customer_ContactActionPerformed

    private void AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeActionPerformed

    private void customer_CityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_CityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customer_CityActionPerformed

    private void customer_StateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_StateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customer_StateActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void Last_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Last_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Last_NameActionPerformed

    private void customer_PincodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_PincodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customer_PincodeActionPerformed

    private void customer_DistrictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_DistrictActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customer_DistrictActionPerformed

    private void registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseClicked
       
        
        String Fname= First_Name.getText();
        String Lname= Last_Name.getText();
        String Email= customer_Email_ID.getText();
        String Cont= customer_Contact.getText();
        String Dob= DOB.getText();
        String Ag= Age.getText();
        String Addr= customer_Address.getText();
        String City= customer_City.getText();
        String Dist= customer_District.getText();
        String State= customer_State.getText();
        String Pin= customer_Pincode.getText();
        String password = new String(customer_password.getPassword());
        String confpassword = new String(confpass.getPassword());
        if(Fname.equals("")){
            JOptionPane.showMessageDialog(null, "Please Enter Your First Name");  
        }
        else if(Lname.equals("")){
            JOptionPane.showMessageDialog(null, "Please Enter Your Last Name");  
        }
        else if(Email.equals("")){
            JOptionPane.showMessageDialog(null, "Please Enter Your Email ID");                   
        }
        else if(Cont.equals("")){
            JOptionPane.showMessageDialog(null, "Please Enter Your Contact");
        }
        else if(Dob.equals("")){
            JOptionPane.showMessageDialog(null, "Please Enter Your Date of Birth");                            
        }
        else if(Ag.equals("")){
            JOptionPane.showMessageDialog(null, "Please Enter Your Age");                               
        }
        else if(Addr.equals("")){
            JOptionPane.showMessageDialog(null, "Please Enter Your Address");                                    
        }
        else if(City.equals("")){
            JOptionPane.showMessageDialog(null, "Please Enter Your City");                                       
        }
        else if(Dist.equals("")){
            JOptionPane.showMessageDialog(null, "Please Enter Your District");
        }
        else if(State.equals("")){
            JOptionPane.showMessageDialog(null, "Please Enter Your State");                                                
        }
        else if(Pin.equals("")){
            JOptionPane.showMessageDialog(null, "Please Enter Your Pincode");                                                    
        }
        else if(password.equals("")){
            JOptionPane.showMessageDialog(null, "Please Enter Your Password"); 
        }
        else if(confpassword.equals("")){
            JOptionPane.showMessageDialog(null, "Please Enter Your Confirm Password");
        }
        else{
            try{
                String query = "INSERT INTO `customer`(`First_Name`, `Last_Name`, `customer_Email_ID`, `customer_password`, `DOB`, `Age`, `Gender`, `customer_Contact`, `customer_Address`, `customer_City`, `customer_District`, `customer_State`, `customer_Pincode`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
                con = DriverManager.getConnection("jdbc:mysql://localhost/lpg booking management system 1","root","");
                pst = con.prepareStatement(query);
                pst.setString(1, First_Name.getText());
                pst.setString(2, Last_Name.getText());
                pst.setString(3, customer_Email_ID.getText());
                pst.setString(4, customer_password.getText());
                pst.setString(5, DOB.getText());
                pst.setString(6, Age.getText());
                pst.setString(7, Gender.getSelectedItem().toString());
                pst.setString(8, customer_Contact.getText());
                pst.setString(9, customer_Address.getText());
                pst.setString(10, customer_City.getText());
                pst.setString(11, customer_District.getText());
                pst.setString(12, customer_State.getText());
                pst.setString(13, customer_Pincode.getText());
            
                if(password.length() > 7 && password.length() < 21)
                {
                    int digit=0, spchar=0, upper = 0; char c;
                    String special = "!@#$%^&*()-_=+`~|{[]};:\\\'\"/?<>,."; 
                    for(int i=0;i<password.length();i++)
                    {
			c=password.charAt(i); 
			if(Character.isDigit(c))
   			{
				digit++;
  		 	}
                        if(Character.isUpperCase(c))
   			{
				upper++;
  		 	}
			if(special.indexOf(c)!=-1)
   			{
				spchar++;
   			}
                    }
                    if ((password.length()>=8)&&(digit>=1)&&(spchar>=1)&&(upper>=1)){
                        if (password.equals(confpassword)){
                            pst.executeUpdate();
                            JOptionPane.showMessageDialog(this, "Registered Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                            home as = new home();
                            as.show();
                            dispose();
                        }else{
                            JOptionPane.showMessageDialog(this, "Password and Confirm Password Do not Match", "Registratin Failed", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                    else{
                        if(digit<1){
                            JOptionPane.showMessageDialog(this, "Password should contain atleast one digit", "", JOptionPane.ERROR_MESSAGE);
                        }
                        else if(spchar<1){
                            JOptionPane.showMessageDialog(this, "Password should contain atleast one special character", "", JOptionPane.ERROR_MESSAGE);
                        }
                        else {
                            JOptionPane.showMessageDialog(this, "Password should contain atleast one upper case character", "", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                }
                else
                {
                    if(password.length() <= 7)
                    {
                        JOptionPane.showMessageDialog(this, "Password Too Small", "", JOptionPane.ERROR_MESSAGE);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "Password Too Big", "", JOptionPane.ERROR_MESSAGE);
                    }
                }
                }catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex);
            }
        }
        
//        try{
//              String query ="INSERT INTO `customer`(`First_Name`, `Last_Name`, `customer_Email_ID`, `customer_password`,`DOB`,`Age`, `Gender`, `customer_Contact`, `customer_Address`, `customer_City`, `customer_District`, `customer_State`, `customer_Pincode`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)";
//          con = DriverManager.getConnection("jdbc:mysql://localhost/lpg booking management system 1","root","");
//          pst =(PreparedStatement) con.prepareStatement(query);
//          pst.setString(1,First_Name.getText());
//          pst.setString(2,Last_Name.getText());
//          pst.setString(3,customer_Email_ID.getText());
//          pst.setString(4,customer_password.getText());
//          pst.setString(5,DOB.getText());
//          pst.setString(6,Age.getText());
//          pst.setString(7,Gender.getSelectedItem().toString());
//          pst.setString(8,customer_Contact.getText());
//          pst.setString(9,customer_Address.getText());
//          pst.setString(10,customer_City.getText());
//          pst.setString(11,customer_District.getText());
//          pst.setString(12,customer_State.getText());
//          pst.setString(13,customer_Pincode.getText());
//     
//          if (password.equals(confpassword)){
//                pst.executeUpdate();
//                JOptionPane.showMessageDialog(this, "Registered Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
//            }else{
//                JOptionPane.showMessageDialog(this, "Check Your Password", "Registratin Failed", JOptionPane.ERROR_MESSAGE);
//            }
//                
//          
//          }  catch (Exception ex){
//              JOptionPane.showMessageDialog(null, ex);
//          
//          }
        
    }//GEN-LAST:event_registerMouseClicked

    private void AgeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AgeFocusGained
Age.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_AgeFocusGained

    private void First_NameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_First_NameFocusGained
First_Name.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_First_NameFocusGained

    private void Last_NameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Last_NameFocusGained
Last_Name.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_Last_NameFocusGained

    private void GenderFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_GenderFocusGained
Gender.getSelectedItem().toString();        // TODO add your handling code here:
    }//GEN-LAST:event_GenderFocusGained

    private void customer_Email_IDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customer_Email_IDFocusGained
   customer_Email_ID.setText("");   // TODO add your handling code here:
    }//GEN-LAST:event_customer_Email_IDFocusGained

    private void customer_ContactFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customer_ContactFocusGained
     customer_Contact.setText("");  // TODO add your handling code here:
    }//GEN-LAST:event_customer_ContactFocusGained

    private void DOBFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DOBFocusGained
      DOB.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_DOBFocusGained

    private void customer_AddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customer_AddressFocusGained
customer_Address.setText("");       // TODO add your handling code here:
    }//GEN-LAST:event_customer_AddressFocusGained

    private void customer_CityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customer_CityFocusGained
   customer_City.setText("");     // TODO add your handling code here:
    }//GEN-LAST:event_customer_CityFocusGained

    private void customer_DistrictFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customer_DistrictFocusGained
customer_District.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_customer_DistrictFocusGained

    private void customer_StateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customer_StateFocusGained
customer_State.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_customer_StateFocusGained

    private void customer_PincodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customer_PincodeFocusGained
customer_Pincode.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_customer_PincodeFocusGained

    private void customer_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customer_passwordFocusGained
customer_password.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_customer_passwordFocusGained

    private void customer_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customer_passwordActionPerformed

    private void confpassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confpassFocusGained
confpass.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_confpassFocusGained

    private void ckpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckpassActionPerformed
    if(ckpass.isSelected()){
            customer_password.setEchoChar((char)0);
        }
        else{
            customer_password.setEchoChar('*');
        }
    }//GEN-LAST:event_ckpassActionPerformed

    private void ckpassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckpassMouseClicked

    }//GEN-LAST:event_ckpassMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(custreg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(custreg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(custreg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(custreg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new custreg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Age;
    private javax.swing.JFormattedTextField DOB;
    private javax.swing.JTextField First_Name;
    private javax.swing.JComboBox<String> Gender;
    private javax.swing.JTextField Last_Name;
    private javax.swing.JCheckBox ckpass;
    private javax.swing.JPasswordField confpass;
    private javax.swing.JTextField customer_Address;
    private javax.swing.JTextField customer_City;
    private javax.swing.JTextField customer_Contact;
    private javax.swing.JTextField customer_District;
    private javax.swing.JTextField customer_Email_ID;
    private javax.swing.JTextField customer_Pincode;
    private javax.swing.JTextField customer_State;
    private javax.swing.JPasswordField customer_password;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private rojerusan.RSFotoCircle rSFotoCircle1;
    private javax.swing.JLabel register;
    // End of variables declaration//GEN-END:variables
}
